### ISSUE TITLE
Use css modules "compose" instead of joining arrays

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#167]
Throughout the app we've been combining styles like this 
`client/src/components/background/background.js`
```
<div
        className={[classes.waveWrapper, classes.waveAnimation].join(" ")}
        style={{ bottom: bottomSpace }}
      >
```
This is not the proper way to combine classes with css modules. It makes the code bloated and hard to read. Instead of doing this in the JSX we should use the "compose" functionality. For example...
`client/src/components/background/background.css`
```css
.waveWrapper {
  overflow: hidden;
  position: absolute;
  left: 0;
  right: 0;
  bottom: 40%;
  top: 0;
  margin: auto;
}

.waveAnimation {
  composes: waveWrapper
  /** ...styles specific to waveAnimation**/
}
```
and now our component looks like this
`client/src/components/background/background.js`
```
<div
  className={classes.waveAnimation}
  style={{ bottom: bottomSpace }}
>
```
There are some instance where we will need to leave the .join() methods. 
Any time we are combining font-awesome classes... 
e.g. `<i className={["fas fa-exclamation-circle", classes.Ntf].join(" ")} />` we need to leave them like this so css modules does not dynamically rename the font-awesome classNames. 

Also in `client/src/layout/workspace/workspace.js` we need to keep this "graph" class so that GeoGebra can fit the graph to the element. 

`<div className={[classes.Top, "graph"].join(" ")}>`

All other .join(" ") statements should be replaced by using composition in the css file.
